pipeline {
    environment {
        IMG_TAG="${sh(script: 'echo \$GIT_COMMIT | cut -c -7 | tr -d \'[:space:]\' ', returnStdout: true ) }"
        APP_NAME="idrs-frontend"
    }

    agent {
        dockerfile {
            dir 'jenkins/'
        }
    }

    stages {

       
        stage('Install Dependencies'){
            steps{
                sh 'env'
                sh 'npm i'
            }
        }

        stage('Run tests'){
            steps{
                sh 'npm t'
             }
        }


        stage('Deploy - onPrem'){
            parallel{
                stage('Deploy to Dev') {
                    when { branch 'dev' }
                    steps {
                        echo "Deploying"
                        sleep 20
                        echo "deployed"
 
               
                    }
                }

                stage('Deploy to QA') {
                    when { branch 'qa' }
                    steps {
                        echo "Deploying"
                        sleep 20
                        echo "deployed"
                    }
                }



            }
        }
    }
    post {

        always {
            cleanWs()
        }
    }
}
